services:
  app:
    image: django_app1
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - app-postgres


  app-postgres:
    image: postgres:15-alpine
    ports:
      - "5432":"5432"
    volumes:
      - "app-postgress:/var/lib/postresql/data"
    environment:
      POSTGRES_DB : django_app
      POSTGRES_USER : user1
      POSTGRESS_PASSWORD : password1

  stt_nginx:
      image: nginx:alpine
      container_name: stt_nginx
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/conf.d:/etc/nginx/conf.d:ro
        - ./static:/app/static
        - ./media:/app/media
        - ./nginx/certbot/conf:/etc/letsencrypt
        - ./nginx/certbot/www:/var/www/certbot
      depends_on:
        - stt_django
      networks:
        - backend
      restart: always

volumes:
  app-postgres:
    name : "app-postgres"