# Generated by Django 6.0.1 on 2026-01-28 20:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('telegram_token', models.CharField(blank=True, max_length=100)),
                ('deleted', models.BooleanField(default=False)),
                ('gpt_model', models.CharField(default='gpt-4o', max_length=50)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=500)),
                ('system_prompt', models.TextField(default='You are a helpful assistant.')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='api.bot')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('prompt_template', models.TextField(help_text='Может содержать шаблоны: {user_input}, {context} и т.д.')),
                ('expected_input_type', models.CharField(choices=[('text', 'Text'), ('choice', 'Choice from buttons'), ('email', 'Email'), ('phone', 'Phone number')], default='text', max_length=50)),
                ('buttons_json', models.JSONField(blank=True, help_text="Telegram inline buttons: [{'text': 'Yes', 'callback': 'yes'}]", null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('next_step_on_success', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_steps', to='api.step')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.scenario')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('scenario', 'order')},
            },
        ),
    ]
